# Generated by Django 5.0.2 on 2024-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage_productimage_unique_product_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='photos/products'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'images'), name='unique_product_image'),
        ),
    ]
