# Generated by Django 5.0.2 on 2024-02-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_productimage_unique_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_product_image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
    ]
