# Generated by Django 5.0.3 on 2024-03-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_wishlist_variations_wishlist_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='variations',
        ),
    ]
