# Generated by Django 5.0.3 on 2024-03-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
