# Generated by Django 5.0.3 on 2024-04-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='category_image',
        ),
    ]
