# Generated by Django 5.0.3 on 2024-05-15 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_cat_image_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
