# Generated by Django 5.0.3 on 2024-03-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_payment_order_payment_orderproduct_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
