# Generated by Django 5.0.3 on 2024-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_variation_orderproduct_variations'),
        ('store', '0007_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(null=True, to='store.variation'),
        ),
    ]
