# Generated by Django 5.0.3 on 2024-03-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_coupon_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
